### ISSUE TITLE
Add missing Swift examples to PFQueryTableViewController Docs

### ISSUE THREAD

**Issue by derekgould** [ParsePlatform/Docs#182] opened 2015-08-20 13:16 UTC
When reviewing the docs for this section, selecting "Swift' as the language on a code window causes all code examples to disappear completely. Reproduced in Edge, Google Chrome, IE and Firefox (on Windows 10).

**Comment by hramos** [comment] 2015-08-20 17:52
I was able to reproduce. It looks like a couple of objc blocks are missing the Swift equivalent, therefore nothing is displayed in those cases. This should be fixed by adding the Swift code example. Can you send a PR?

**Comment by derekgould** [comment] 2015-08-20 17:55
Sorrywhats a PR?

 

 

Regards,

DG

____________________________________________________________________________
______

Never hold discussions with the monkey when the organ grinder is in the
room.
-Winston Churchill

**Comment by hramos** [comment] 2015-08-21 18:04
A pull request is how you propose updates to our documentation repo. You can read more in our CONTRIBUTING file: https://github.com/ParsePlatform/Docs/blob/master/CONTRIBUTING.md

**Closed** 2016-02-01 18:44 UTC
Labels: good first task
