### ISSUE TITLE
📙 Change mLab references to MongoDB

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/Docs#766] opened 2020-09-10 10:41 UTC
__Link to section:__
https://docs.parseplatform.org/parse-server/guide/#deploying-to-glitch-and-mlab

__What is the issue?__
mLab has been bought by MongoDB, the mLab brand is discontinued; mLab does not allow to sign up for new accounts.

__Can you propose a solution?__
Change refs from mLab to MongoDB, as they also provide a free sandbox plan.

**Comment by TomWFox** [comment] 2020-09-10 11:46
Duplicate of #704

**Closed as completed by TomWFox** 2020-09-10 11:46 UTC
Labels: type:docs
